server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://cinema-db:5432/movie_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
