server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://cinema-db:5432/movie_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
